### ISSUE TITLE
NodeJS app throws ORA-12560 error when deployed in OCI

### ISSUE THREAD

**Issue by alan-czajkowski** [oracle/node-oracledb#1343]
# What versions are you using?

Connecting to Oracle DB in Oracle Cloud Infrastructure (OCI)

# Describe the problem

NodeJS app is built with NestJS. This app is being deployed to a Kubernetes (K8s) cluster inside OCI. This app connects to an Oracle DB inside OCI. On startup, the NodeJS app throws this error:
```
Error: ORA-12560: TNS:protocol adapter error
```

# Include a runnable Node.js script that shows the problem.

**`package.json`**:
```
...
  "dependencies": {
    ...
    "oracledb": "^5.0.0",
...
```

**`Dockerfile`**:
```
FROM node:14.15-slim

USER root

# install/update OS packages
RUN apt-get update \
 && apt-get install -y libaio1 \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* \
           /tmp/* \
           /var/tmp/*

# download & install Oracle libraries
ARG INSTANT_CLIENT_VERSION="21.1.0.0.0"
ARG INSTANT_CLIENT_FILENAME="instantclient-basic-linux.x64-${INSTANT_CLIENT_VERSION}.zip"
ARG INSTANT_CLIENT_CKSUM="532775708"
ARG INSTANT_CLIENT_BYTES="79250994"
RUN mkdir -p /opt/oracle \
 && cd /opt/oracle \
 && wget https://download.oracle.com/otn_software/linux/instantclient/$(echo ${INSTANT_CLIENT_VERSION} | tr -d .)/${INSTANT_CLIENT_FILENAME} \
 && /bin/bash -c "[ \"${INSTANT_CLIENT_CKSUM} ${INSTANT_CLIENT_BYTES}\" == \"$(cksum ${INSTANT_CLIENT_FILENAME} | awk '{print $1, $2}')\" ]" \
 && unzip -oq ${INSTANT_CLIENT_FILENAME} \
 && /bin/sh -c "echo /opt/oracle/instantclient_$(echo ${INSTANT_CLIENT_VERSION} | tr . ' ' | awk '{print $1"_"$2}') > /etc/ld.so.conf.d/oracle-instantclient.conf" \
 && ldconfig

# ... some more commands here

CMD [ "/bin/sh", "-c", "node dist/src/main" ]
```

# Notes
- in the **kustomize** **`sealedsecret.yaml`**:
```
kind: "SealedSecret"
apiVersion: "bitnami.com/v1alpha1"
metadata:
  name: "ss-node-oci-wallet"
spec:
  template:
    metadata:
      name: "dev-ss-node-oci-wallet"
  encryptedData:
    cwallet.sso: "..."
    ewallet.p12: "..."
    keystore.jks: "..."
    ojdbc.properties: "..."
    sqlnet.ora: "..."
    tnsnames.ora: "..."
    truststore.jks: "..."
status: { }

```
- in the **kustomize** **`deployment.yaml`**, we are volume mounting the Oracle Wallet:
```
...
          volumeMounts:
            - name: "secret-volume"
              mountPath: "/wallet"
...
      volumes:
        - name: "secret-volume"
          secret:
            secretName: "dev-ss-node-oci-wallet"
...
```
- `TNS_ADMIN=/wallet` is being passed in as an environment variable on container startup
